mode = "client"
log_level = "debug" # optional

[trojan]
password = "password"

[socks5]
addr = "127.0.0.1:1080"

[tls]
addr = "example.com:443"
sni = "example.com"
cert = "cert.pem" # optional
cipher = ["TLS13_AES_128_GCM_SHA256"] # optional
#cipher = ["TLS13_CHACHA20_POLY1305_SHA256","TLS13_AES_256_GCM_SHA384","TLS13_AES_128_GCM_SHA256","TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256","TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256","TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA25"]

# optional
#[websocket]
#uri = "wss://example.com/trojanpath"

# optional
#[mux]
#concurrent = 8
#timeout = 30
