on: [push]

#name: ARM build
name: msvc rust

jobs:
  msvc_build:
    name: msvc_build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        env:
          RUSTFLAGS: -C target-cpu=amdfam10
        run: 
          cargo build --release

      - uses: actions/upload-artifact@v2
        with:
          name: trojan-r
          path: target/release/trojan-r.exe
          

#jobs:
#  linux_arm:
#    name: Linux ARM
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          target: aarch64-linux-android
#          override: true
#      - uses: actions-rs/cargo@v1
#        with:
#          use-cross: true
#          env: 
#            RUSTFLAGS='-C target-cpu=cortex-a53'
#          command: build
#          args: --release -v --target aarch64-linux-android
#      - uses: actions/upload-artifact@v2
#        with:
#           name: trojan-r
#           path: target/aarch64-linux-android/release/trojan-r
